### ISSUE TITLE
RANSAC Fails to Detect Model - Need More Lidar Points

### ISSUE THREAD

**Issue by zayedrmdn** [acfr/cam_lidar_calibration#64]
I'm encountering an issue with the cam_lidar_calibration package on ROS Noetic. The package correctly detects the chessboard, but when I try to 'Capture Sample,' I get these errors:

```
[pcl::SampleConsensusModel::getSamples] Can not select 0 unique points out of 1!
[pcl::RandomSampleConsensus::computeModel] No samples could be selected!
[pcl::RandomSampleConsensus::computeModel] RANSAC found no model.
[pcl::SACSegmentation::segment] Error segmenting the model! No solution found.
[ERROR] [1723617562.542058090]: RANSAC unsuccessful, discarding sample - Need more lidar points on board
```
**System Information:**
- OS: Ubuntu 20.04
- ROS Version: Noetic (ROS1)
- Branch: noetic-v2
- Lidar: RSLIDAR
- Camera: USB Camera

**Configuration (cfg/params.yaml):**
```
# Topics
camera_topic: "/usb_cam/image_raw"
camera_info: "/usb_cam/camera_info"
lidar_topic: "/rslidar_points"

# Feature Extraction Settings
feature_extraction:
  x_min: 1.0
  x_max: 7.0
  y_min: -3.0
  y_max: 3.0
  z_min: -1.7
  z_max: 0.0
  k: 50
  z: 1
  voxel_res: 0.4

# Chessboard Calibration Target
chessboard:
  pattern_size:
    height: 5
    width: 7
  square_length: 95
  board_dimension:
    width: 700.5
    height: 1000
  translation_error:
    x: 2
    y: 2
```
**Troubleshooting Done:**
1. Tried different voxel_res values.
2. Adjusted rqt_reconfigure bounds.
3. Attempted to convert RSLIDAR points to Velodyne points. This resulted in no chessboard detection from the camera image, but no RANSAC-related errors were present.

**Request:**
Can you provide advice on how to fix this? Is there a specific setting or adjustment needed to get enough LIDAR points for RANSAC?

Screenshots:
![Screenshot](https://github.com/user-attachments/assets/d77224ca-5698-4d33-bf61-04ff4032c697)
![Screenshot_terminal](https://github.com/user-attachments/assets/7297c0cc-1b20-49ae-980a-383cd1453e0c)
